-- camanishgupta.com content tables, for the shared Supabase project.
--
-- HOW TO USE: copy this file into hotel-finance-book/supabase/migrations/ and
-- apply it from that repo, so one repo owns every migration on the database.
-- Do not run `supabase db push` from the portfolio repo.
--
-- Security model: the portfolio site uses only the publishable (anon) key.
-- Anonymous visitors can SELECT published rows from portfolio_* tables and
-- nothing else. Editing happens in the Supabase dashboard (Table Editor) or a
-- future admin page using the service role, never from the public site.

-- ---------------------------------------------------------------------------
-- Single-row settings
-- ---------------------------------------------------------------------------
create table if not exists public.portfolio_settings (
  id smallint primary key default 1 check (id = 1),
  hero_eyebrow text not null default '',
  hero_before text not null default '',
  hero_emphasis text not null default '',
  hero_after text not null default '',
  hero_intro text not null default '',
  now_caption text not null default '',
  portrait_url text,
  record_checked_on text not null default '',
  about_heading text not null default '',
  about_intro text not null default '',
  contact_email text not null default '',
  linkedin_url text,
  speaking_topics text[] not null default '{}',
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Ordered, publishable collections
-- ---------------------------------------------------------------------------
create table if not exists public.portfolio_record_items (
  id bigint generated by default as identity primary key,
  label text not null,
  value text not null,
  is_total boolean not null default false,
  source_url text,
  sort_order integer not null default 100,
  published boolean not null default true
);

create table if not exists public.portfolio_disciplines (
  id bigint generated by default as identity primary key,
  label text not null,
  proof text not null,
  sort_order integer not null default 100,
  published boolean not null default true
);

create table if not exists public.portfolio_offers (
  id bigint generated by default as identity primary key,
  audience text not null,
  title text not null,
  description text not null,
  formats text not null default '',
  status text not null default 'open' check (status in ('open', 'waitlist')),
  cta_label text not null default 'Get in touch',
  cta_url text not null default '#notes',
  waitlist_note text,
  sort_order integer not null default 100,
  published boolean not null default true
);

create table if not exists public.portfolio_sessions (
  id bigint generated by default as identity primary key,
  title text not null,
  audience text not null default '',
  date_label text not null default '',
  status text not null default 'upcoming' check (status in ('upcoming', 'recorded')),
  url text,
  sort_order integer not null default 100,
  published boolean not null default true
);

create table if not exists public.portfolio_projects (
  id bigint generated by default as identity primary key,
  name text not null,
  status text not null default 'prototype' check (status in ('idea', 'prototype', 'beta', 'live')),
  summary text not null default '',
  url text,
  url_label text,
  case_study_url text,
  featured boolean not null default false,
  sort_order integer not null default 100,
  published boolean not null default true
);

create table if not exists public.portfolio_platforms (
  id bigint generated by default as identity primary key,
  platform text not null,
  summary text not null,
  url text,
  sort_order integer not null default 100,
  published boolean not null default true
);

create table if not exists public.portfolio_courses (
  id bigint generated by default as identity primary key,
  platform text not null,
  title text not null,
  stats text not null default '',
  referral_url text,   -- instructor referral link; the site prefers this
  public_url text,
  sort_order integer not null default 100,
  published boolean not null default true
);

create table if not exists public.portfolio_books (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  theme text not null default 'reporting'
    check (theme in ('reporting', 'budgeting', 'playbook', 'leadership', 'independent', 'ai')),
  url text,            -- leave empty to link to book.ehotelmanagementschool.com/books/<slug>
  sort_order integer not null default 100,
  published boolean not null default true
);

create table if not exists public.portfolio_appearances (
  id bigint generated by default as identity primary key,
  show_name text not null,
  link_label text not null default 'Listen',
  url text,
  sort_order integer not null default 100,
  published boolean not null default true
);

create table if not exists public.portfolio_career (
  id bigint generated by default as identity primary key,
  period text not null,
  role text not null,
  detail text not null default '',
  sort_order integer not null default 100,
  published boolean not null default true
);

create table if not exists public.portfolio_podcast_pages (
  slug text primary key check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  show_name text not null,
  intro text not null default '',
  -- [{"kind":"Guide","title":"...","label":"eHMS Press","url":"https://..."}]
  resources jsonb not null default '[]'::jsonb,
  sort_order integer not null default 100,
  published boolean not null default true
);

-- ---------------------------------------------------------------------------
-- Row-level security: public read of published rows only
-- ---------------------------------------------------------------------------
do $$
declare
  t text;
begin
  foreach t in array array[
    'portfolio_settings', 'portfolio_record_items', 'portfolio_disciplines', 'portfolio_offers',
    'portfolio_sessions', 'portfolio_projects', 'portfolio_platforms', 'portfolio_courses',
    'portfolio_books', 'portfolio_appearances', 'portfolio_career', 'portfolio_podcast_pages'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all privileges on public.%I from anon, authenticated', t);
    execute format('grant select on public.%I to anon, authenticated', t);
    execute format('grant all on public.%I to service_role', t);
    execute format('drop policy if exists "Public can read published rows" on public.%I', t);
    if t = 'portfolio_settings' then
      execute format('create policy "Public can read published rows" on public.%I for select to anon, authenticated using (true)', t);
    else
      execute format('create policy "Public can read published rows" on public.%I for select to anon, authenticated using (published)', t);
    end if;
  end loop;
end
$$;

-- ---------------------------------------------------------------------------
-- Public image folder for the portrait and project screenshots.
-- Upload through the dashboard; the public URL goes into the table.
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('portfolio', 'portfolio', true)
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- One email list: allow a "portfolio" lead type in reader_leads.
-- Pair this with adding "portfolio" to allowedTypes in app/api/leads/route.ts.
-- That type does not start the hotel-book chapter emails.
-- ---------------------------------------------------------------------------
alter table public.reader_leads drop constraint if exists reader_leads_type_check;
alter table public.reader_leads
  add constraint reader_leads_type_check
  check (type in ('newsletter', 'contact', 'book-launch', 'portfolio'));

-- ---------------------------------------------------------------------------
-- Starting content (matches the site's built-in sample content)
-- ---------------------------------------------------------------------------
insert into public.portfolio_settings (
  id, hero_eyebrow, hero_before, hero_emphasis, hero_after, hero_intro, now_caption,
  record_checked_on, about_heading, about_intro, contact_email, speaking_topics
) values (
  1,
  'Group CFO · Chartered Accountant · Author',
  'The CFO who has also ', 'run the hotel', '.',
  'Twenty-three years across hotel finance, operations and technology, from Shangri-La to Group CFO. I write the Hotel Finance Practice Library and help finance teams put AI to work without losing their judgement.',
  'Group CFO, CHIC, NAIA & Muzuri · hotels, real estate and retail, DRC',
  '6 Oct 2026',
  'Accountant by training, operator by habit.',
  'I am a Chartered Accountant and Company Secretary with 23 years in finance: audit in Delhi, Shangri-La in Bangkok and Chiang Mai, then CFO roles in Myanmar and the DRC. Along the way I have run hotel operations as well as their books. I care less about finance as compliance and more about finance as a decision system: clear numbers, useful analysis, accountability and action.',
  '[hello@camanishgupta.com]',
  array[
    'How finance teams can use AI without losing judgement',
    'From reporting numbers to influencing decisions',
    'What hospitality teaches us about operating discipline',
    'Turning experience into books, courses and tools'
  ]
) on conflict (id) do nothing;

insert into public.portfolio_record_items (label, value, is_total, source_url, sort_order)
select * from (values
  ('Learners on Udemy', '146,065', false, 'https://www.udemy.com/user/manish-224/', 10),
  ('Learners on Alison', '114,925', false, 'https://alison.com/publisher/manish-gupta', 20),
  ('Enrolments, Udemy and Alison', '260,990', true, null, 30),
  ('Courses on Coursera', '19', false, 'https://www.coursera.org/instructor/~139904014', 40),
  ('Years in finance, 17 of them in hotels', '23', false, null, 50),
  ('Hotel Finance Practice Library', '5 books · 4 guides', false, 'https://book.ehotelmanagementschool.com', 60),
  ('Recognition', 'Top 10 CFOs in Asia, 2024', false, null, 70)
) as v(label, value, is_total, source_url, sort_order)
where not exists (select 1 from public.portfolio_record_items);

insert into public.portfolio_disciplines (label, proof, sort_order)
select * from (values
  ('Hotel finance', 'Assistant FC at Shangri-La Bangkok to Group CFO across hotels, malls and retail.', 10),
  ('Operations', 'Task-force Resident Manager for Shangri-La. Ran hotel operations in the CEO''s absence from 2021.', 20),
  ('Technology', 'Led an ERP rollout across 15 hotels and brought in revenue management systems.', 30),
  ('AI', 'GenAI finance courses on Coursera. Building the Hotel Finance Workspace and close automations.', 40)
) as v(label, proof, sort_order)
where not exists (select 1 from public.portfolio_disciplines);

insert into public.portfolio_offers (audience, title, description, formats, status, cta_label, cta_url, waitlist_note, sort_order)
select * from (values
  ('For finance teams', 'AI sessions', 'Talks and workshops on using AI for analysis, forecasting and reporting, with the review controls finance work needs.', 'Keynote · Half-day workshop · Team programme', 'open', 'Plan a session', '#sessions', null, 10),
  ('For finance managers', 'Mentoring', 'One-to-one support for finance managers moving toward CFO: commercial judgement, owner and board reporting, leadership presence.', '[FORMAT, e.g. monthly 1:1 over six months]', 'open', 'Apply for mentoring', '#notes', null, 20),
  ('For owners', 'Advisory', 'Selective finance advisory for hotel owners and growing businesses: reporting that owners can act on, budgets, cash and controls.', 'Reporting review · Budget and forecast · Fractional CFO', 'waitlist', 'Join the waitlist', '#notes', 'Opening [MONTH YEAR]. Join the list to hear first.', 30)
) as v(audience, title, description, formats, status, cta_label, cta_url, waitlist_note, sort_order)
where not exists (select 1 from public.portfolio_offers);

insert into public.portfolio_sessions (title, audience, date_label, status, sort_order)
select * from (values
  ('GenAI for financial forecasting and planning', 'Live online · Finance teams', '[DATE]', 'upcoming', 10),
  ('Using AI in the month-end close', 'Workshop · Controllers and accountants', '[DATE]', 'upcoming', 20),
  ('GenAI for financial data analysis', 'Recording and slides', 'Recorded', 'recorded', 30)
) as v(title, audience, date_label, status, sort_order)
where not exists (select 1 from public.portfolio_sessions);

insert into public.portfolio_projects (name, status, summary, url, url_label, featured, sort_order)
select * from (values
  ('eHMS Hotel Finance Workspace', 'beta', 'Budget, forecast, actuals and owner reporting for independent hotels, in one place instead of a dozen spreadsheets.', 'https://app.ehotelmanagementschool.com', 'Try the demo', true, 10),
  ('Month-end close assistant', 'prototype', '', null, null, false, 20),
  ('Supplier reconciliation to Xero journals', 'prototype', '', null, null, false, 30)
) as v(name, status, summary, url, url_label, featured, sort_order)
where not exists (select 1 from public.portfolio_projects);

insert into public.portfolio_platforms (platform, summary, url, sort_order)
select * from (values
  ('Udemy', '146,065 learners and 2,368 reviews, from hotel finance to financial analysis', 'https://www.udemy.com/user/manish-224/', 10),
  ('Udemy', 'Hotel Management School profile · [LEARNERS AND COURSES]', null, 20),
  ('Coursera', '19 courses with Starweaver, from Mastering Hotel Financials to GenAI for Financial Forecasting', 'https://www.coursera.org/instructor/~139904014', 30),
  ('Alison', '9 courses, 114,925 learners, including data analysis with Power BI and hospitality cash management', 'https://alison.com/publisher/manish-gupta', 40),
  ('eHMS', 'Hotel Menu Engineering · How to Read a Hotel P&L in 20 Minutes', 'https://book.ehotelmanagementschool.com', 50)
) as v(platform, summary, url, sort_order)
where not exists (select 1 from public.portfolio_platforms);

insert into public.portfolio_courses (platform, title, stats, referral_url, public_url, sort_order)
select * from (values
  ('Udemy', '[Top Udemy course]', '[learners] · [rating]', null, null, 10),
  ('Coursera', 'Mastering Hotel Financials', '4,256 learners · 4.8 from 17 reviews', null, 'https://coursera.org/learn/mastering-hotel-financials', 20),
  ('Alison', 'Financial Modelling in Decision-Making and Business Planning', '24,787 learners', null, 'https://alison.com/publisher/manish-gupta', 30)
) as v(platform, title, stats, referral_url, public_url, sort_order)
where not exists (select 1 from public.portfolio_courses);

insert into public.portfolio_books (slug, title, theme, sort_order)
values
  ('hotel-financial-reporting-in-practice', 'Hotel Financial Reporting in Practice', 'reporting', 10),
  ('hotel-budgeting-and-forecasting', 'Hotel Budgeting and Forecasting in Practice', 'budgeting', 20),
  ('hotel-operations-financial-playbook', 'Hotel Operations Financial Playbook', 'playbook', 30),
  ('from-finance-manager-to-cfo', 'From Finance Manager to CFO', 'leadership', 40),
  ('independent-hotel-finance-made-simple', 'Independent Hotel Finance Made Simple', 'independent', 50)
on conflict (slug) do nothing;

insert into public.portfolio_appearances (show_name, link_label, sort_order)
select * from (values ('Daily Mastermind', 'Listen', 10), ('Valiant CEO', 'Read', 20)) as v(show_name, link_label, sort_order)
where not exists (select 1 from public.portfolio_appearances);

insert into public.portfolio_career (period, role, detail, sort_order)
select * from (values
  ('2025–now', 'Group CFO', 'CHIC, NAIA & Muzuri, DRC. Hotels operated by Accor, malls, residential and franchised retail.', 10),
  ('2017–2025', 'CFO', 'Myanmar Treasure Hotel and Resort. ERP across 15 hotels; ran operations in the CEO''s absence from 2021.', 20),
  ('2009–2016', 'Shangri-La Hotels and Resorts', 'Assistant FC in Bangkok, Financial Controller in Chiang Mai, task-force Resident Manager in Yangon, Manila and Boracay.', 30),
  ('2001–2009', 'Audit and finance', 'Delhi. T R Chadha & Co. and Basundhra Properties.', 40),
  ('Alongside', 'Founder', 'eHotel Management School and eHMS Press.', 50)
) as v(period, role, detail, sort_order)
where not exists (select 1 from public.portfolio_career);

insert into public.portfolio_podcast_pages (slug, show_name, intro, resources)
values (
  'default', 'podcast',
  'Everything I mentioned on the episode is below, plus one free thing I promised.',
  '[
    {"kind":"Guide","title":"13-Week Cash Flow for Hotels","label":"eHMS Press","url":"https://book.ehotelmanagementschool.com/decision-guides"},
    {"kind":"Tool","title":"Hotel Finance Workspace demo","label":"Beta","url":"https://app.ehotelmanagementschool.com"},
    {"kind":"Session","title":"How finance teams can use AI without losing judgement","label":"AI sessions","url":"/#sessions"}
  ]'::jsonb
) on conflict (slug) do nothing;
